/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Mavsel;

import java.awt.TextField;
import javax.swing.JPasswordField;


/**
 *
 * @author ie
 */
public class MavselWizardSwing1 extends javax.swing.JPanel {

    /**
     * Creates new form MavselWizardSwing1
     */
    public MavselWizardSwing1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelURL = new java.awt.Label();
        textFieldURL = new java.awt.TextField();
        textFieldPort = new java.awt.TextField();
        textFieldUser = new java.awt.TextField();
        labelPort = new java.awt.Label();
        labelPassword = new java.awt.Label();
        labelUser = new java.awt.Label();
        jPasswordFieldPassword = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelTitle = new javax.swing.JLabel();

        labelURL.setText(org.openide.util.NbBundle.getMessage(MavselWizardSwing1.class, "MavselWizardSwing1.labelURL.text")); // NOI18N

        textFieldURL.setText(org.openide.util.NbBundle.getMessage(MavselWizardSwing1.class, "MavselWizardSwing1.textFieldURL.text")); // NOI18N

        textFieldPort.setText(org.openide.util.NbBundle.getMessage(MavselWizardSwing1.class, "MavselWizardSwing1.textFieldPort.text")); // NOI18N

        textFieldUser.setText(org.openide.util.NbBundle.getMessage(MavselWizardSwing1.class, "MavselWizardSwing1.textFieldUser.text")); // NOI18N

        labelPort.setText(org.openide.util.NbBundle.getMessage(MavselWizardSwing1.class, "MavselWizardSwing1.labelPort.text")); // NOI18N

        labelPassword.setText(org.openide.util.NbBundle.getMessage(MavselWizardSwing1.class, "MavselWizardSwing1.labelPassword.text")); // NOI18N

        labelUser.setText(org.openide.util.NbBundle.getMessage(MavselWizardSwing1.class, "MavselWizardSwing1.labelUser.text")); // NOI18N

        jPasswordFieldPassword.setText(org.openide.util.NbBundle.getMessage(MavselWizardSwing1.class, "MavselWizardSwing1.jPasswordFieldPassword.text")); // NOI18N
        jPasswordFieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldPasswordActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTitle.setText(org.openide.util.NbBundle.getMessage(MavselWizardSwing1.class, "MavselWizardSwing1.jLabelTitle.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldURL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textFieldPort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textFieldUser, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(jPasswordFieldPassword))
                .addGap(186, 186, 186))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textFieldURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelURL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textFieldPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPort, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        labelURL.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(MavselWizardSwing1.class, "MavselWizardSwing1.label1.AccessibleContext.accessibleName")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordFieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldPasswordActionPerformed

    public void unsetup(MavselSpigot importer) {
        //Configure the importer
        //Example
        //importer.setOption(optionCheckbox.isSelected());
        importer.setUrl(textFieldURL.getText());
        importer.setPort(textFieldPort.getText());
        importer.setUser(textFieldUser.getText());
        importer.setPassword(jPasswordFieldPassword.getPassword().toString());
    }

    public JPasswordField getjPasswordFieldPassword() {
        return jPasswordFieldPassword;
    }

    public TextField getTextFieldPort() {
        return textFieldPort;
    }

    public TextField getTextFieldURL() {
        return textFieldURL;
    }

    public TextField getTextFieldUser() {
        return textFieldUser;
    }
    
    @Override
    public String getName() {
 
        return "MAVSEL - Connection setup";
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPasswordField jPasswordFieldPassword;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.Label labelPassword;
    private java.awt.Label labelPort;
    private java.awt.Label labelURL;
    private java.awt.Label labelUser;
    private java.awt.TextField textFieldPort;
    private java.awt.TextField textFieldURL;
    private java.awt.TextField textFieldUser;
    // End of variables declaration//GEN-END:variables
}
