/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Mavsel;

import org.openide.util.NbBundle;

/**
 *
 * @author ie
 */
public class MavselWizardSwing2 extends javax.swing.JPanel {

    /**
     * Creates new form MavselWizardSwing2
     */
    public MavselWizardSwing2() {
        initComponents();
    }
    
    @Override
    public String getName() {
        
        return "MAVSEL - Data selection";
    }
    
    public void unsetup(MavselSpigot importer) {
        //Configure the importer
        //Example
        //importer.setOption(optionCheckbox.isSelected());
       /* importer.setUrl(textFieldURL.getText());
        importer.setPort(textFieldPort.getText());
        importer.setUser(textFieldUser.getText());
        importer.setPassword(jPasswordFieldPassword.getSelectedText());*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText(org.openide.util.NbBundle.getMessage(MavselWizardSwing2.class, "MavselWizardSwing2.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel1)
                .addContainerGap(208, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addContainerGap(243, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
